config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'foods#index'
  resources :foods do
      resources :photos, only: :create
  end
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :comments
  has_many :photos
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :picture, PictureUploader
  
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  def index
    @foods = Food.order("name")
  end

  def new
    @foods = Food.new
  end

  def create
    Food.create(food_params)
    redirect_to root_path
  end

  def show
    @food = Food.find(params[:id])
    @photo = Photo.new
  end

  private

  def food_params
    params.require(:food).permit(:name, :description, :country)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def create
    @food = Food.find(params[:food_id])
    @food_photos.create(photo_params)
    redirect_to food_path(@food)
  end

  private

  def photo_params
    params.require(:photo).permit(:caption, :picture)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/foods/index.html.erb
<% @foods.each do |food| %>
  <div class="booyah-box col-10 offset-1">
    <h1><%= link_to food.name, food_path(food) %></h1><br />
    <i><%= food.description %></i><br />
    <p><%= food.country %></p><br />
   
  </div>

<% end %>

app/views/foods/new.html.erb
 <div class="booyah-box col-10 offset-1"> 
  <h1>Create a new favorite ethnic dish</h1>

  <%= simple_form_for @foods do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :country %>
    
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>

</div>

app/views/foods/show.html.erb
<div class="booyah-box col-10 offset-1">
  <h1><%= @food.name %></h1>
  <i><%= @food.description %></i>
  <br/><br/>
  <p><%= @food.country %></p>


  <!-- Modal for Photos-->
<div class="modal fade" id="myPhotoModal" tabindex="-1" role="dialog" aria-labelledby="myPhotoModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="myModalLabel">Add photo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <%= simple_form_for @photo, url: food_photos_path(@food) do |f| %>
      <div class="modal-body">
        <%= f.input :picture %>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      <%= f.submit "Save Changes", class: 'btn btn-primary' %>
      </div>
    <% end %>
    </div>
  </div>
</div>

<div class="col-10">
<h1 class="float-left">Photos</h1>
<br /><br /><br />
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-md float-left" data-toggle="modal" data-target="#myPhotoModal">
  Add photo
</button>

<div class="clear"></div>

<div class="row">
  <% @food.photos.each do |photo| %>
    <div class="col-12 col-sm-6">
      <blockquote>
        <%= image_tag photo.picture %>
        <br />
        <%= photo.caption %>
      </blockquote>
    </div>
  <% end %>
</div>
</div>


</div>


<br /><br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ethnicfood</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<div id="flex-content-container">
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
     
      <%= link_to 'Far Flung Food', root_path, class: 'navbar-brand' %>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to new_food_path, class: 'nav-link' do %>
              <i class="fa fa-plus-circle"></i>
              New Food
            <% end %>
          </li>
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </div>

  <div id="footer">
      <div class="container">
        <b>Footer Here</b>
        <br />
        <%= link_to 'Link', '#' %>
      </div>
    </div>
  </body>
</html>